name: CI

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        dcompiler: [dmd-latest, dmd-beta, dmd-master, dmd-2.088.0, dmd-2.087.1, dmd-2.086.1, ldc-latest, ldc-beta, ldc-master]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Install ${{ matrix.dcompiler }}
      uses: WebFreak001/setup-dlang@releases/v0_webfreak
      with:
        compiler: ${{ matrix.dcompiler }}
    - name: Build
      run: dub build
    #- name: Start MongoDB
    #  run: mongod --bind_ip 127.0.0.1 --fork
    #- name: Run tests
    #  run: dub test
