name: CI

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        dcompiler: [dmd-latest, dmd-beta, dmd-master, dmd-2.094.2, ldc-latest, ldc-beta, ldc-master]
        os: [ubuntu-latest, windows-latest, macOS-13]

    steps:
    - uses: actions/checkout@v2
    - name: Install ${{ matrix.dcompiler }}
      uses: dlang-community/setup-dlang@v1
      with:
        compiler: ${{ matrix.dcompiler }}
    - name: Build
      run: dub build
    #- name: Start MongoDB
    #  run: mongod --bind_ip 127.0.0.1 --fork
    #- name: Run tests
    #  run: dub test
