name: CI

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        dmd_version: [2.088.0, 2.087.1, 2.086.1]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Install DMD ${{ matrix.dmd_version }}
      uses: WebFreak001/setup-dmd@releases/v1
      with:
        dmd-version: ${{ matrix.dmd_version }}
    - name: Build
      run: dub build
    #- name: Start MongoDB
    #  run: mongod --bind_ip 127.0.0.1 --fork
    #- name: Run tests
    #  run: dub test
